name: lms
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  font_awesome_flutter: ^10.10.0
  get_it: ^8.2.0
  go_router: ^16.2.4
  google_fonts: ^6.3.2
  image_picker: ^1.2.0
  image: ^4.0.21
  lottie: ^3.3.2
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  toastification: ^3.0.3
  pinput: ^5.0.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
